global:
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  evaluation_interval: 15s
scrape_configs:
- job_name: ssv
  metrics_path: /metrics
  static_configs:
  - targets:
    - "ssv-node:15000"
  relabel_configs:
  - target_label: pod
    replacement: ssv-node-1
